spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zhukelili.com:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: jian031018
    filters: wall,mergeStat
    data-source-name: gunsdb

#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zhukelili.com:3306/guns_test_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: jian031018
    data-source-name: otherdb
